[package]
name = "rust-gstreamer-recording"
version = "0.1.0"
edition = "2021"

[dependencies]
gstreamer = "0.23.3"
gstreamer-video = "0.23.3"
glib = "0.20.3"
ctrlc = "3.4.5"
nix = "0.29.0"
ordered-float = "4.5.0"
